### ISSUE TITLE
not compiling on mac os 11.16.1

### ISSUE THREAD

**Issue by vanbalen** [woutgg/ofxGenericDmx#14]
I get the following error: 

of_v0.11.2/addons/ofxGenericDmx/src/DmxUsbProDevice.cpp:204:3: Non-constant-expression cannot be narrowed from type 'unsigned int' to 'unsigned char' in initializer list

on these 2 lines: 
```
int r;
	unsigned char reqParams[2] = {
		userConfigLength & 0xFF,
		( userConfigLength >> 8	) & 0xFF
```

(I'm an OF newbie and first time playing with DMX, using enttec dmx pro usb)

**Comment by woutgg** [comment]
Hi,

That seems to be due to changes in more recent compiler versions, I happened to run into it myself with another project.

I have not tried it myself, but this should fix it:

```c++
unsigned char reqParams[2] = {
	static_cast<unsigned char>(userConfigLength & 0xFF),
	static_cast<unsigned char>(( userConfigLength >> 8 ) & 0xFF)
};
```

Please let me know if that fixes it, and good luck with your DMX endeavours. :)

**Comment by vanbalen** [comment]
thnx so much, that worked!

**Comment by woutgg** [comment]
You're welcome!
