### ISSUE TITLE
building in Raspberry Pi 2 

### ISSUE THREAD

**Issue by eloimaduell** [woutgg/ofxGenericDmx#7]
Hi ! 

I'm trying to build ofxGenericDMX for the Raspberry Pi and i'm facing several errors i can't solve.

If i "make" as it is ... I get : 

ion `FtdiDevice::setBaudRate(int) const':
FtdiDevice.cpp:(.text+0x3c): undefined reference to`ftdi_set_baudrate'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function `FtdiDevice::setLineProperties(FtdiDevice::FTDI_DATABITS_TYPE, FtdiDevice::FTDI_STOPBITS_TYPE, FtdiDevice::FTDI_PARITY_TYPE, FtdiDevice::FTDI_BREAK_TYPE) const':
FtdiDevice.cpp:(.text+0x9c): undefined reference to`ftdi_set_line_property2'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function `FtdiDevice::setFlowControl(FtdiDevice::FTDI_FLOWCTL_TYPE) const':
FtdiDevice.cpp:(.text+0xc0): undefined reference to`ftdi_setflowctrl'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function `FtdiDevice::reset() const':
FtdiDevice.cpp:(.text+0xe8): undefined reference to`ftdi_usb_reset'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function `FtdiDevice::setRts(bool) const':
FtdiDevice.cpp:(.text+0x140): undefined reference to`ftdi_setrts'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function `FtdiDevice::setDtr(bool) const':
FtdiDevice.cpp:(.text+0x174): undefined reference to`ftdi_setdtr'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function `FtdiDevice::purgeBuffers(int) const':
FtdiDevice.cpp:(.text+0x1bc): undefined reference to`ftdi_usb_purge_buffers'
FtdiDevice.cpp:(.text+0x1c8): undefined reference to `ftdi_usb_purge_tx_buffer'
FtdiDevice.cpp:(.text+0x1f4): undefined reference to`ftdi_usb_purge_rx_buffer'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function `FtdiDevice::close()':
FtdiDevice.cpp:(.text+0x28c): undefined reference to`ftdi_usb_close'
FtdiDevice.cpp:(.text+0x2ac): undefined reference to `ftdi_free'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function`FtdiDevice::getLastError() const':
FtdiDevice.cpp:(.text+0x308): undefined reference to `ftdi_get_error_string'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function`FtdiDevice::readData(unsigned char const_, int, int) const':
FtdiDevice.cpp:(.text+0x3d0): undefined reference to `ftdi_read_data'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function`FtdiDevice::writeData(unsigned char const_, int) const':
FtdiDevice.cpp:(.text+0x464): undefined reference to `ftdi_write_data'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function`FtdiDevice::freeDeviceList()':
FtdiDevice.cpp:(.text+0x52c): undefined reference to `ftdi_list_free'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function`FtdiDevice::fetchUsbInformation(ftdi_context_, libusb_device_)':
FtdiDevice.cpp:(.text+0x5a4): undefined reference to `ftdi_usb_get_strings'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function`FtdiDevice::getDeviceList(ftdi_context_)':
FtdiDevice.cpp:(.text+0x654): undefined reference to `ftdi_usb_find_all'
FtdiDevice.cpp:(.text+0x718): undefined reference to`ftdi_free'
FtdiDevice.cpp:(.text+0x720): undefined reference to `ftdi_new'
../../../addons/obj/linuxarmv7l/Release/ofxGenericDmx/src/FtdiDevice.o: In function`FtdiDevice::open(char const_, char const_, int)':
FtdiDevice.cpp:(.text+0x780): undefined reference to `ftdi_new'
FtdiDevice.cpp:(.text+0x8ac): undefined reference to`ftdi_usb_open_dev'
collect2: ld returned 1 exit status
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:296: recipe for target 'bin/ofxGenericDmx_EnttecDmxUsbProExample' failed
make[1]: *_\* [bin/ofxGenericDmx_EnttecDmxUsbProExample] Error 1

My guess is that for some reason the Makefile is not including or linking against the "libftdi1.a" ?
Should i include it on the config.make ?
So I try it ... i added the libftdi1.a on the USER_LD_FLAGS ... And now the error after cleaning and rebuilding with make is :+1: 

/usr/bin/ld: /home/pi/openframeworks/addons/ofxGenericDmx/libs/libftdi1/lib/linux/libftdi1.a(ftdi.c.o):
Relocations in generic ELF (EM: 3)
/usr/bin/ld: /home/pi/openframeworks/addons/ofxGenericDmx/libs/libftdi1/lib/linux/libftdi1.a(ftdi.c.o):
Relocations in generic ELF (EM: 3)
/usr/bin/ld: /home/pi/openframeworks/addons/ofxGenericDmx/libs/libftdi1/lib/linux/libftdi1.a(ftdi.c.o):
Relocations in generic ELF (EM: 3)
/usr/bin/ld: /home/pi/openframeworks/addons/ofxGenericDmx/libs/libftdi1/lib/linux/libftdi1.a(ftdi.c.o):
Relocations in generic ELF (EM: 3)
/usr/bin/ld: /home/pi/openframeworks/addons/ofxGenericDmx/libs/libftdi1/lib/linux/libftdi1.a(ftdi.c.o):
Relocations in generic ELF (EM: 3)
/usr/bin/ld: /home/pi/openframeworks/addons/ofxGenericDmx/libs/libftdi1/lib/linux/libftdi1.a(ftdi.c.o):
Relocations in generic ELF (EM: 3)
/home/pi/openframeworks/addons/ofxGenericDmx/libs/libftdi1/lib/linux/libftdi1.a:
error adding symbols: File in wrong format
collect2: ld returned 1 exit status
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:296:
recipe for target 'bin/ofxGenericDmx_EnttecDmxUsbProExample' failed
make[1]: **\* [bin/ofxGenericDmx_EnttecDmxUsbProExample] Error 1

Does anyone have a clue of what i'm doing wrong ? 
Should i recompile the libftdi1.a for the Raspberry ? or the one included as Linux should work ?

Any hints very appreciated ... whiling to test this on the Raspberry ...

**Comment by woutgg** [comment]
Hi,

You are thinking in the right direction. The included libftdi1.a is built for intel-64 processors, while the rPi contains an ARM processor. So yes, you should recompile libftdi1, see [scripts/building-libs-howto.txt](https://github.com/woutgg/ofxGenericDmx/blob/master/scripts/building-libs-howto.txt).

Since we've obviously never tried to use the addon on an rPi, the Makefile might fail.
Let me know how far you get. And if you can build it successfully, we would appreciate it if you share how you did it so we can update the readme with instructions.

**Comment by pierrep** [comment]
I just wanted to write that I've used this addon extensively with RPi's, from the RPi1 all the way to the RPi3. It's the only DMX addon that works flawlessly (Kyle's one has issues under Linux).

To get it working, all you need to do is add the ftdi library:

`sudo apt-get install libftdi`

Then just add the following lines to the config.make file:

`PROJECT_LDFLAGS=-Wl,-rpath=./libs
PROJECT_LDFLAGS+=-lftdi`

The idea of compiling open source libs usually only makes sense on Windows or OSX. Linux distros include them through package managers making the process super easy.

Honestly this issue should be closed...feel free to add this info to the Readme.

**Comment by pierrep** [comment]
Also - regarding Makefiles, I have never tried the ones included in the examples. Just use the project generator to make a new project for you and use that. This is the best practice on Linux or RPi...that way the Makefile is always the latest version.

**Comment by timolden** [comment]
Thanks Pierre, that's great to hear!
